CC = gcc -Wall -Werror -Wextra

door_struct :
    $(CC) -o ../build/Quest_1 dmanager_module.c
list_test :
    $(CC) -o ../build/Quest_2 list.c list_test.c
stack_test :
    $(CC) -o ../build/Quest_3 stack.c stack_test.c
rebuild :
    clean door_struct list_test stack_test
clean :
    rm *.o ../build/Quest_1 ../build/Quest_2 ../build/Quest_3